version: "3"

services:
  workspace:
    container_name: ws
    image: python:3.10-slim
    volumes:
      - .:/ws

  django:
    container_name: django
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: local
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "80:8000"
    volumes:
      - ./src:/django

  database:
    container_name: database
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./.docker/database:/docker-entrypoint-initdb.d

volumes:
  postgresql_data: null
